{
	"version": 1725750728,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/btnachievement-sheet0.png",
		"images/btnleaderboard-sheet0.png",
		"images/btnads-sheet0.png",
		"images/btnsound-sheet0.png",
		"images/btnsound-sheet1.png",
		"images/btnmusic-sheet0.png",
		"images/btnmusic-sheet1.png",
		"images/btnoption-sheet0.png",
		"images/btnresume-sheet0.png",
		"images/btnhome-sheet0.png",
		"images/btnkiz10-sheet0.png",
		"images/btnplay-sheet0.png",
		"images/btnretry-sheet0.png",
		"images/btnbuydollar-sheet0.png",
		"images/btnnext-sheet0.png",
		"images/btnprev-sheet0.png",
		"images/btnshopdollar-sheet0.png",
		"images/btnplaygame-sheet0.png",
		"images/btnupgrade-sheet0.png",
		"images/btnupgradeback-sheet0.png",
		"images/btnupgradecolor-sheet0.png",
		"images/btnupgradetype-sheet0.png",
		"images/btnupgradetype-sheet1.png",
		"images/btnskip-sheet0.png",
		"images/btnnextgame-sheet0.png",
		"images/btnup-sheet0.png",
		"images/btndown-sheet0.png",
		"images/btnboost-sheet0.png",
		"images/btnok-sheet0.png",
		"images/bg1-sheet0.png",
		"images/bgbuildingfront1-sheet0.png",
		"images/bgbuildingback1-sheet0.png",
		"images/bgsidewalk1.png",
		"images/bgroad1.png",
		"images/bgcloud1-sheet0.png",
		"images/bg2-sheet0.png",
		"images/bgcloud2-sheet0.png",
		"images/bgroad2.png",
		"images/bgsidewalk2.png",
		"images/bgparkfront-sheet0.png",
		"images/bgbuildingback2-sheet0.png",
		"images/bgparkback-sheet0.png",
		"images/bg3-sheet0.png",
		"images/bgcloud3-sheet0.png",
		"images/bgbuildingback3-sheet0.png",
		"images/bgbridgefront-sheet0.png",
		"images/bgmoon-sheet0.png",
		"images/bgbridgeback-sheet0.png",
		"images/txtdollar.png",
		"images/txtdollarbuy.png",
		"images/txttotaldollar.png",
		"images/txtstaticblack.png",
		"images/txtstaticwhite.png",
		"images/txtwarning.png",
		"images/bgpreloader-sheet0.png",
		"images/uiloading-sheet0.png",
		"images/fresult-sheet0.png",
		"images/transition-sheet0.png",
		"images/spr1024x450-sheet0.png",
		"images/rotatescreen-sheet0.png",
		"images/cam-sheet0.png",
		"images/flashwhite-sheet0.png",
		"images/flashred-sheet0.png",
		"images/foption-sheet0.png",
		"images/uidistance-sheet0.png",
		"images/uivelocity-sheet0.png",
		"images/uialtitude-sheet0.png",
		"images/barback-sheet0.png",
		"images/barfront-sheet0.png",
		"images/bar-sheet0.png",
		"images/game-sheet0.png",
		"images/objsolid-sheet0.png",
		"images/starblue-sheet0.png",
		"images/starbig-sheet0.png",
		"images/crane-sheet0.png",
		"images/crane-sheet1.png",
		"images/crane-sheet2.png",
		"images/windmill-sheet0.png",
		"images/posbtnboost-sheet0.png",
		"images/plane0-sheet0.png",
		"images/plane1-sheet0.png",
		"images/plane2-sheet0.png",
		"images/plane3-sheet0.png",
		"images/vfxstarbig.png",
		"images/vfxplane.png",
		"images/vfxplaneboost.png",
		"images/vfxboost-sheet0.png",
		"images/vfxboost-sheet1.png",
		"images/vfxboost-sheet2.png",
		"images/uibuydollar-sheet0.png",
		"images/uidollar-sheet0.png",
		"images/fshopdollar-sheet0.png",
		"images/uititle-sheet0.png",
		"images/mainmenucrane-sheet0.png",
		"images/mainmenucrane-sheet1.png",
		"images/mainmenucrane-sheet2.png",
		"images/mainmenuplane-sheet0.png",
		"images/mainmenuwindmill-sheet0.png",
		"images/mainmenustarblue-sheet0.png",
		"images/mainmenustarbig-sheet0.png",
		"images/map-sheet0.png",
		"images/map-sheet1.png",
		"images/mapbgback-sheet0.png",
		"images/mapbgfront-sheet0.png",
		"images/mapfmilleage-sheet0.png",
		"images/mapplane-sheet0.png",
		"images/mapdistance-sheet0.png",
		"images/upgradebg-sheet0.png",
		"images/upgradeprogressframe-sheet0.png",
		"images/upgradeday-sheet0.png",
		"images/upgradeplaneframe-sheet0.png",
		"images/upgradecolorframe-sheet0.png",
		"images/upgradeframe-sheet0.png",
		"images/upgradetitle-sheet0.png",
		"images/upgradeprogressbarbg-sheet0.png",
		"images/upgradeplanebg-sheet0.png",
		"images/upgradeplane-sheet0.png",
		"images/upgradedescriptionframe-sheet0.png",
		"images/upgradeprogressbar-sheet0.png",
		"images/upgradeprogressbarline.png",
		"images/upgradeprogressbardot-sheet0.png",
		"images/upgrademaxlabel-sheet0.png",
		"images/upgradeframedollar-sheet0.png",
		"images/tutorkeyboard-sheet0.png",
		"images/tutorarrow-sheet0.png",
		"images/tutorialtouch-sheet0.png",
		"images/rotatescreensheet-sheet0.png",
		"media/in game.m4a",
		"media/in game.ogg",
		"media/menu.m4a",
		"media/menu.ogg",
		"media/button prev next.m4a",
		"media/button prev next.ogg",
		"media/button.m4a",
		"media/button.ogg",
		"media/buy.m4a",
		"media/dollar.m4a",
		"media/dollar.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/lose.m4a",
		"media/lose.ogg",
		"media/deactive.m4a",
		"media/deactive.ogg",
		"media/power up.m4a",
		"media/power up.ogg",
		"media/select.m4a",
		"media/select.ogg",
		"media/win.m4a",
		"media/win.ogg",
		"media/buy.ogg",
		"media/collision ground.m4a",
		"media/collision ground.ogg",
		"media/crane.m4a",
		"media/crane.ogg",
		"media/plane fall.m4a",
		"media/plane fall.ogg",
		"media/stalling.m4a",
		"media/stalling.ogg",
		"media/star big boost.m4a",
		"media/star big boost.ogg",
		"media/star big.m4a",
		"media/star big.ogg",
		"media/throw.m4a",
		"media/throw.ogg",
		"media/windmill.m4a",
		"media/windmill.ogg",
		"media/collision ground init.m4a",
		"media/collision ground init.ogg",
		"media/score total.m4a",
		"media/score total.ogg",
		"media/score.m4a",
		"media/score.ogg",
		"media/move.m4a",
		"media/move.ogg",
		"media/number.m4a",
		"media/number.ogg",
		"media/boost.m4a",
		"media/boost.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}